db:
  image: postgres
  ports:
    - 5432:5432
  env_file: .env
app:
  build: .
  command: lein ring server-headless
  ports:
    - "5001:5001"
    - "7001:7001"
  volumes:
    - .:/usr/src/clnote
  links:
    - db
